# 👑 Royal GitHub Sponsors Config - Lord Rahl Edition

github: ["LordRahl2-sys"]
thanks_dev: ["gh/LordRahl2-sys"]

# 💠 Additional Sponsorship Platforms
# Enable and update the lines below to activate them

# patreon: [lordrahl]
# open_collective: [lordrahl-collective]
# ko_fi: [lordrahl]
# tidelift: [https://tidelift.com/funding/github/rahl-backend]
# custom: ["https://rahl.tech/sponsor"]
